[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "FgmCt9nkSv5reTBfQdHEukmwe2d6bhyvXXeKJbjUm7WS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
